### ISSUE TITLE
If you can't sleep, just count sheep!!

### ISSUE THREAD

**Issue by antonos4o** [antonos4o/Soft-Uni-Fundamentals#123]
**IN A NEW FILE**

Create a function that, given a non-negative integer, 3 for example, prints a string with a murmur: "1 sheep...2 sheep...3 sheep...". Input will always be valid, i.e. no negative integers.

**Comment by Urvi-Pandit** [comment]
Please assign this issue to me

**Comment by Urvi-Pandit** [comment]
Please assign this issue to me

**Comment by Urvi-Pandit** [comment]
Sorry I unassigned by mistake.... Please consider me
