### ISSUE TITLE
Odd Number Checker

### ISSUE THREAD

**Issue by antonos4o** [antonos4o/Soft-Uni-Fundamentals#23]
**IN A NEW FILE**

Create a function that checks if a number is odd and prints out true if it is, false otherwise.

**Comment by VaibhavKambar7** [comment]
hey, can i work on this?

**Comment by antonos4o** [comment]
Yes just make sure to create a new branch and link the brand to the issue.

На пт, 22.09.2023 г., 21:07 Vaibhav Kambar ***@***.***>
написа:
